name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pip install poetry
      - name: Install deps
        run: poetry install
      - name: Lint
        run: poetry run ruff nidus_scraper tests
      - name: Type check
        run: poetry run mypy nidus_scraper
      - name: Test
        run: poetry run pytest -q
